# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('military', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
