# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0002_building_tatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='tatus',
            new_name='status',
        ),
    ]
