# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0003_auto_20180910_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.CharField(blank=True, default='loading', max_length=30, null=True),
        ),
    ]
