# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0003_profile_towns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
