# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0004_auto_20180906_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='towns',
        ),
        migrations.AddField(
            model_name='towns',
            name='whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appName.Profile'),
        ),
    ]
