# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0005_auto_20180906_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='appName.Profile'),
        ),
    ]
