# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0005_remove_profile_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
