# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 14:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0006_building_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='resources',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
