# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0007_towns_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
                ('tier', models.IntegerField(blank=True, default=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='preparing', max_length=30, null=True)),
                ('town_position', models.CharField(blank=True, max_length=30)),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='appName.Towns')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
