# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0008_auto_20180921_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
