# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0009_auto_20180921_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troop',
            name='town_position',
        ),
    ]
