# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0010_remove_troop_town_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='town_position',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
