# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0011_troop_town_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('loading', 'Under construction'), ('completed', 'Completed')], default='loading', max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('timber', 'Timber'), ('main', 'Main building'), ('stone', 'Quarry'), ('barrack', 'Barrack'), ('stable', 'Stable'), ('farm', 'Farm'), ('depot', 'Depot')], max_length=30),
        ),
        migrations.AlterField(
            model_name='troop',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready to fight')], default='preparing', max_length=30),
        ),
        migrations.AlterField(
            model_name='troop',
            name='tier',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='troop',
            name='type',
            field=models.CharField(choices=[('lander', 'Lander'), ('cavalry', 'Cavalry'), ('bowman', 'Archer')], max_length=30),
        ),
    ]
