# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0013_auto_20180921_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set([('town', 'type')]),
        ),
    ]
