# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0014_auto_20180921_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('timber', 'Timber'), ('main', 'Main building'), ('stone', 'Quarry'), ('barrack', 'Barrack'), ('stable', 'Stable'), ('farm', 'Farm'), ('depot', 'Depot'), ('house', 'House')], max_length=30),
        ),
    ]
