# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0016_auto_20180921_2211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='zone',
            name='town',
        ),
        migrations.RemoveField(
            model_name='troop',
            name='town_zone',
        ),
        migrations.AddField(
            model_name='troop',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='appName.Towns'),
        ),
        migrations.AddField(
            model_name='troop',
            name='town_position',
            field=models.CharField(blank=True, choices=[('north', 'Defend North'), ('south', 'Defend South'), ('west', 'Defend West'), ('east', 'Defend East'), ('center', 'Defend Town Center')], default='center', max_length=30),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
