# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0017_auto_20180921_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='type',
            field=models.CharField(choices=[('lander', 'Lander'), ('cavalry', 'Cavalry'), ('archer', 'Archer')], max_length=30),
        ),
    ]
