# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0020_auto_20180923_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='building_queue',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='towns',
            name='troop_queue',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
