# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0022_auto_20180923_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('timber', 'Timber'), ('main', 'Main building'), ('stone', 'Quarry'), ('barrack', 'Barrack'), ('stable', 'Stable'), ('farm', 'Farm'), ('depot', 'Depot'), ('house', 'House'), ('archery', 'Archery')], max_length=30),
        ),
    ]
