# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0023_auto_20180924_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='x_coord',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='towns',
            name='y_coord',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='towns',
            name='building_process_limit',
        ),
        migrations.RemoveField(
            model_name='towns',
            name='military_process_limit',
        ),
        migrations.AlterUniqueTogether(
            name='towns',
            unique_together=set([('x_coord', 'y_coord')]),
        ),
    ]
