# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0024_auto_20180927_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('loading', 'Under construction'), ('completed', 'Completed')], default='completed', max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='town',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='appName.Towns'),
        ),
        migrations.AlterField(
            model_name='towns',
            name='building_queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='towns',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='towns',
            name='resources',
            field=jsonfield.fields.JSONField(default={'food': 1000, 'stone': 1000, 'wood': 1000}),
        ),
        migrations.AlterField(
            model_name='towns',
            name='troop_queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='towns',
            name='x_coord',
            field=models.IntegerField(default=81, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='towns',
            name='y_coord',
            field=models.IntegerField(default=185, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='troop',
            name='tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='troop',
            name='town',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='appName.Towns'),
        ),
        migrations.AlterField(
            model_name='troop',
            name='town_position',
            field=models.CharField(choices=[('north', 'Defend North'), ('south', 'Defend South'), ('west', 'Defend West'), ('east', 'Defend East'), ('center', 'Defend Town Center')], default='center', max_length=30),
        ),
    ]
