# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0026_auto_20180927_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='resources',
            field=jsonfield.fields.JSONField(default="{'wood': 1000, 'food': 1000, 'stone': 1000}"),
        ),
        migrations.AlterField(
            model_name='towns',
            name='x_coord',
            field=models.IntegerField(default=45, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='towns',
            name='y_coord',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
