# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 09:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0028_auto_20180927_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='towns',
            name='x_coord',
            field=models.IntegerField(default=219, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='towns',
            name='y_coord',
            field=models.IntegerField(default=205, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
