# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 11:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0029_auto_20180928_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='x_coord',
            field=models.IntegerField(default=172, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='towns',
            name='y_coord',
            field=models.IntegerField(default=278, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
