# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 07:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0031_auto_20180929_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('timber', 'Timber'), ('main', 'Main building'), ('stone', 'Quarry'), ('barrack', 'Barrack'), ('stable', 'Stable'), ('farm', 'Farm'), ('depot', 'Depot'), ('house', 'House'), ('archery', 'Archery'), ('workshop', 'Demirci'), ('shelter', 'Shelter'), ('wall', 'Wall')], max_length=30),
        ),
        migrations.AlterField(
            model_name='towns',
            name='x_coord',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='towns',
            name='y_coord',
            field=models.IntegerField(default=144, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='troop',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready')], default='preparing', max_length=30),
        ),
    ]
